name: Publish Docker image

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3
      
      - name: Update Minor version
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'MINOR'
          value: $((${{ secrets.MINOR }}+1))
          repository: marwane8/muslim-league-api
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Debug
        run: |
          echo "Value of secrets.MINOR: ${{ secrets.MINOR }}"
          echo "Incremented value: $((${{ secrets.MINOR }}+1))"

      - name: Build and Push 
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ml-api:1.${{ secrets.MINOR }}
      
