name: Python Test

on:
  push:
    branches: ["feature"]
  pull_request:
    branches: ["feature"]

jobs:
  build:
  
    runs-on: ubuntu-latest
    env:
      USERS_DB_URL: ${{ github.workspace }}/database/users.db
      BBALL_DB_URL: ${{ github.workspace }}/database/bball.db
      SOCCER_DB_URL: ${{ github.workspace }}/database/soccer.db

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies 
        run: |
          python  -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest  
